on:
  push:
    branches:
      - master

name: Build and deploy on push to master
jobs:

  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@master

      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install

      - name: shalzz/zola-deploy-action
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ secrets.TOKEN }}
