on:
  push:
    branches:
      - main

name: Build and deploy on push to main
jobs:

  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install

      - name: shalzz/zola-deploy-action
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ secrets.TOKEN }}
